generic:
  name: 'generic'
  sessions:
    authenticating: "We're checking up on your with Google."
    sign_in: "Welcome back. Now tell your friends about what you're doing."
    sign_out: "You're out. See you again soon."
    timeout: "Sometimes people get signed out for hanging around doing nothing. I guess that's what happened to you."
    already_signed_in: "You're already signed in. You don't need to sign in again."
    already_signed_out: "You can't sign out before you've even signed in."
    
  users:
    signed_up: "Good to see a new face. Now see what your friends are doing and let them know what you're up to."
    sign_up_button: "Sign up"
    already_signed_in: "Your're already signed in. Why are you trying to sign up again?"
    
    updated: "Your profile info has been changed."
    edit_not_you: "You can't edit someone else's profile."
    edit_uid: "YOu can't edit your authentication information."
    
    destroyed: "So sorry you don't want to stay. Come back any time and we'll have a place for you."
    destroy_not_you: "Why are you trying to delete someone else's account? That doesn't seem ethical."

    
  venues:
    new: "Another favorite place added to the list."
    update: "Changes to this venue have been saved."
    deleted: "The venue information was removed. I'm sure it will be missed."
    submit: "Submit"

general:
  name: 'general'
  sessions:
    authenticating: "I'm looking for you on my roll."
    sign_in: 'There you are. Now fall in.'
    sign_out: 'Dismissed!'
    timeout: 'You were caught loitering and tossed out.'
    already_signed_in: "I already know you're here, warrior. Now get to work!"
    already_signed_out: "You haven't even checked in and you're trying to check out?!"

    
  users:
    signed_up: "You've successfully enlisted. Now go kick some ass."
    sign_up_button: "Enlist"
    already_signed_in: "You're already in! You can't re-enlist."

    updated: 'Yeah yeah. I got your personnel info filed. Now quit dallying with the paperwork and get to your ops.'
    edit_not_you: "You can't edit someone else's profile!"
    edit_uid: "The office uses that to verify your identity. You can't change it!"

    destroyed: "You have your discharge. You know where the recruiter is if you want back in."
    destroy_not_you: "You don't have clearence to discharge another recruit!"
    
  venues:
    new: "We got your intel on this new location."
    updated: "Revising our intel on this theater... Good thinking."
    deleted: "That intel was outdated anyway."
    submit: 'File intel'
